Import neon-mentat
victorporof/tofino pull request #61
Opened 2017-04-19 21:22 UTC by bgrins

What this does is set up a dependency for neon-mentat, which allows us to run mentat code in the browser server.  It also has travis run with rust installed and reorganizes the config a bit to accommodate that builds for this branch are at (https://www.travis-ci.org/victorporof/tofino/branches).

It exposes two main functions: `query` and `transact`.  Everything is done in memory for now but eventually you'll be able to pass a string to the constructor for saving to a db.

This doesn't hook up any actual logic beyond a test yet, because building correctly on windows requires some extra work and I want to be careful to not break people's workflow if possible.  What happens if you are on windows without node-gyp or don't have rust installed (on any platform) is the mentat object that gets used is a stubbed out function - so it doesn't break but it also doesn't do anything: https://github.com/bgrins/neon-mentat/blob/master/lib/connection.js.

2017-04-19 21:31 UTC, bgrins commented
@bwinton has kindly volunteered to check and make sure this doesn't break the build on his machine.

The longer term plan to ultimately support and get this running on windows is to install node-gyp as outlined in https://github.com/neon-bindings/neon#requirements

2017-04-20 04:41 UTC, victorporof approved these changes
Brian is killing it.

2017-04-20 04:41 UTC, victorporof commented on src/browser-server/mentat.js
> +
License header here.

2017-04-20 04:41 UTC, victorporof commented on src/browser-server/test/test-mentat.js
> +import expect from 'expect';
Test license header here please.

2017-04-20 04:41 UTC, victorporof commented
Land at will.

2017-04-20 14:29 UTC, bwinton commented
Running `npm run test` on Windows gives:
``` 7 passing (436ms)
  1 failing

  1) mentat should query:

      Error: Expected 0 to equal 1
      + expected - actual

      -0
      +1

      at assert (node_modules\expect\lib\assert.js:29:9)
      at Expectation.toEqual (node_modules\expect\lib\Expectation.js:81:30)
      at Context.<anonymous> (C:/Users/bwinton/Programming/tofino/src/browser-server/test/test-mentat.js:25:34)
```
so, uh, it would be nice if we could get that working before landing.  😉

I also get a bunch of:
```error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed
…
error: Could not compile `libc`.
```
errors running `npm run package` which we should probably fix somehow.  (Maybe by adding rust to our install instructions?  Maybe by making it more optional somehow?)

2017-04-20 14:30 UTC, bwinton requested changes
(Changes as described in my previous comment.)

2017-04-20 14:31 UTC, victorporof commented
@bwinton https://github.com/victorporof/tofino/issues/37 for the win?

2017-04-20 15:16 UTC, bwinton commented
That would definitely help, if someone wanted to set it up…  🙂

2017-04-20 15:55 UTC, bgrins commented
I'll see about setting up appveyor on this branch

2017-04-20 20:42 UTC, bgrins commented
OK @bwinton I think the latest changes on this branch should build and pass `npm test` on windows.  Can you let me know if it works for you?

I also have windows CI running at https://ci.appveyor.com/project/bgrins/tofino, which should be actually building and running the native module.  It also does a package so it should fail if packaging breaks - next step would be to deploy the artifacts somewhere.

2017-04-20 20:43 UTC, bwinton commented
Whoa, conflicts…  Did you want to push a rebased version and I'll test that?  😉

2017-04-20 20:43 UTC, bgrins commented
> Whoa, conflicts… Did you want to push a rebased version and I'll test that?

Done

2017-04-20 21:00 UTC, bwinton approved these changes

2017-04-20 21:00 UTC, bwinton commented
Looks _way_ better.  Thank you!

2017-04-21 09:04 UTC, merged