WIP - add more styles
victorporof/tofino pull request #96
Opened 2017-05-03 21:22 UTC by bwinton

This gets it closer to Shorlander's mockup.  Any suggestions on how to improve it are welcome!

2017-05-05 11:24 UTC, victorporof reviewed
Couple of notes:

With these changes, it's impossible to move the window around after filling the tabbar with tabs.

Filling the tabbar with tabs overflows the window minimize button on Windows and Linux.

On macOS, window controls aren't vertically centered in the tabbar anymore (since it's shorter). Should either make the tabbar taller, or nudge the native controls a little more by using a "onlyTitleBarHidden" window instead of "onlyTitleBarHiddenAndWindowControlsInset".

The window border doesn't respect the fact that windows are curved on macOS, so corners have a few pixels cut.

2017-05-05 15:52 UTC, victorporof requested changes
This is great overall, but there's a few small oddities you may want to address.

2017-05-08 15:43 UTC, ericawright reviewed
Some nits
- could you add the top border to the active tab after the background animation is finished, or slide it up with the animation?
- on Shorlander's mock there is a version with extra drag space.

missing from this:
- More padding/margin on the right side of the close button.
- grey top border with growing animation when hovering over inactive tab
- hover effect on close button

2017-05-08 15:45 UTC, bwinton commented
I asked Stephen about this, and he said that I should use the version without any of the options checked, so no extra drag space in this version.  (Perhaps I'll add an about:visuals options page later to let us toggle stuff.  ;) )

2017-05-09 07:57 UTC, victorporof commented
@bwinton That would be a great exercise for us to 1. Build some about pages and 2. Have some kind of prefs story.

2017-05-11 18:19 UTC, victorporof commented
Is this ready for re-review?

2017-05-11 18:20 UTC, ericawright commented
Almost. Adding a few more changes first. I'll comment here once it's ready.

2017-05-11 19:24 UTC, ericawright commented
@bwinton please test the changes on windows. @victorporof ready for re-review :)

2017-05-11 21:22 UTC, bwinton commented
(I made some minor tweaks on Windows, but other than those, it looks good.)

2017-05-12 12:45 UTC, victorporof approved these changes
Note that when the blue flash tab loading animations are displayed, the selected tab's top blue bar disappears. Your choice if you want to fix that here or in a later PR.

Window controls are still not vertically aligned on macOS, as per https://github.com/victorporof/tofino/pull/96#pullrequestreview-36483871 Again, your choice if you want to address this in this PR or not, but have you tried looking into it? 

Some more style nits below.

2017-05-12 12:45 UTC, victorporof commented on src/browser-frontend/views/browser/chrome/tabbar.css
> +  padding: 0 10px 0 40px;
Any reason why we need both margins and paddings (here and below) to make the tabbar not overflow over window controls? Why not just use one?

2017-05-12 12:46 UTC, victorporof commented on src/browser-frontend/views/browser/chrome/tabbar/new-tab-button.jsx
> -        </div>
With this change, the new tab button contents aren't properly horizontally aligned in the button.
<img width="129" alt="screen shot 2017-05-12 at 2 28 53 pm" src="https://cloud.githubusercontent.com/assets/248899/25998513/a2be75ba-3721-11e7-97c9-3581af1bd8ac.png">

2017-05-12 14:32 UTC, bwinton commented on src/browser-frontend/views/browser/chrome/tabbar/new-tab-button.jsx
> -        </div>
Fixed.

2017-05-12 14:35 UTC, bwinton commented on src/browser-frontend/views/browser/chrome/tabbar.css
> +  padding: 0 10px 0 40px;
Fixed.

2017-05-12 14:48 UTC, bwinton commented
> Note that when the blue flash tab loading animations are displayed, the selected tab's top blue bar disappears. Your choice if you want to fix that here or in a later PR.

New PR.  (It looks like we'll need a new gif from Eric…)

> Window controls are still not vertically aligned on macOS, as per #96 (review) Again, your choice if you want to address this in this PR or not, but have you tried looking into it?

We did, and this is hella-hard to fix.  Possibly impossible, unless we want to draw the macOS windows controls ourselves…

2017-05-12 18:11 UTC, merged